INSERT INTO `localization` (`message_key`, `language`, `message_text`) VALUES ('common.date_format', 'cz', 'd. M. yyyy');
INSERT INTO `localization` (`message_key`, `language`, `message_text`) VALUES ('main.title', 'cz', 'WibeContact');
INSERT INTO `localization` (`message_key`, `language`, `message_text`) VALUES ('main.desire', 'cz', 'Na co máš náladu?');
INSERT INTO `localization` (`message_key`, `language`, `message_text`) VALUES ('main.desire.nothing', 'cz', 'nerušte mě');
INSERT INTO `localization` (`message_key`, `language`, `message_text`) VALUES ('main.desire.walk', 'cz', 'jít ven');
INSERT INTO `localization` (`message_key`, `language`, `message_text`) VALUES ('main.desire.sport', 'cz', 'jít sportovat');
INSERT INTO `localization` (`message_key`, `language`, `message_text`) VALUES ('main.desire.fun', 'cz', 'jít se bavit');
INSERT INTO `localization` (`message_key`, `language`, `message_text`) VALUES ('main.contacts', 'cz', 'Kdo chce také {0}?');
INSERT INTO `localization` (`message_key`, `language`, `message_text`) VALUES ('main.add_contact', 'cz', 'Přidat kontakt');
INSERT INTO `localization` (`message_key`, `language`, `message_text`) VALUES ('main.show_contacts', 'cz', 'Zobrazit kontakty');
INSERT INTO `localization` (`message_key`, `language`, `message_text`) VALUES ('main.before_minutes', 'cz', 'Před {0} minutami');
INSERT INTO `localization` (`message_key`, `language`, `message_text`) VALUES ('main.before_hours', 'cz', 'Před {0} hodinami');
INSERT INTO `localization` (`message_key`, `language`, `message_text`) VALUES ('main.yesterday', 'cz', 'Včera');
INSERT INTO `localization` (`message_key`, `language`, `message_text`) VALUES ('contacts.title', 'cz', 'Kontakty');
INSERT INTO `localization` (`message_key`, `language`, `message_text`) VALUES ('contacts.delete', 'cz', 'Smazat');
INSERT INTO `localization` (`message_key`, `language`, `message_text`) VALUES ('add_contact.title', 'cz', 'Přidat kontakt');
INSERT INTO `localization` (`message_key`, `language`, `message_text`) VALUES ('add_contact.email', 'cz', 'E-mail');
INSERT INTO `localization` (`message_key`, `language`, `message_text`) VALUES ('add_contact.phone', 'cz', 'Telefon');
INSERT INTO `localization` (`message_key`, `language`, `message_text`) VALUES ('add_contact.save', 'cz', 'Uložit kontakt');